sudo: required
services:
  - docker
dist: trusty
language: node_js
node_js:
  - "8"
notifications:
  email: false
install: null
script:
  - ./docker_build
after_success:
  # Fix permissions on node_modules after Docker creates the folder.
  - sudo chown "$(whoami)" node_modules
  - npm install coveralls
  # Fix paths in lcov.info so they match Coveralls' expectation that they were generated on Travis.
  - docker exec zestful-frontend cat /app/coverage/lcov.info | sed --expression='s@^SF:\/app@SF:'"${PWD}"'@g' | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: firebase
  token:
    secure: dM/04Jbx5TWaX/eYQsdEOMFbqBBAEbR6Glikb12E0lGZ4JVlzEw+dK+V0d7zAsZ226+Arhbd5USc/LUmdB+n+CIgzv/5Fyfe/DTeaaw4rce0K2DsolurK1+zfq0eKvzs8VMrIkfnJkGtpk1494k2mCvB6lkFlfNqexhjLGYqwtzRq/1A2CS4x5+Q8BPK/hiN/DPyrRvpYFnX1pGpy+I2siFmm8F/eCg3F+6K/3CngFwQcmsC2M+3Zio424yQerUwVLygxLKvvMymVPutFpaBtBZxr5jU0VeTxZaSTIIu3+u2s0yEjaS+pQ5/mamfZa36nh+q3wkLsJbznKUYbK8AguYfalt4mYO4+TEOgdcwZgqjpRIhT890lMdvsMFRcQtDbFUEOhB1anhFp7PxAB1DJmanROI8Yo54MluiJZP/gu8DJZUrtSo6inxVo3BL6QSrRhOytlCWMw7EPxUEC/MByVZLgjdFf+gUAEsfGxTEX2KvHc96vobSW0NNkpgWxyUpj7ASvJtk/bsAOiz1QVPFTdlPDgC8sVR2LBDRbYp10k3y1Akf4TYG3D+jLWjb6VbHhUy+B8eckcm5PxxsyGVu/KEUdvFoNZDGB7ApiQ1rZZGwVaoy+57++9juO0r24taIgx1zTgN9JdkFHSlcXOC8jM9FLs0PG4twX0jxfmmoqXU=
  skip_cleanup: true
